import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ReactQueryProvider } from './react-query-provider';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import dynamic from 'next/dynamic';

export const metadata = {
  title: 'step-finance-exercise',
  description: 'Generated by create-solana-dapp',
};


const WalletLoader = dynamic(() => import('@/components/solana/wallet-loader'), { ssr: false })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
                <UiLayout links={[]}>
                  <WalletLoader>{children}</WalletLoader>
                </UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
